### ISSUE TITLE
Indenting with spaces instead of tabs

### ISSUE THREAD

**Issue by zurkoxxx** [RiFi2k/format-html-in-php#1]
I have a problem. 
Is there any way to make the extension use spaces instead of tabs for formatting?

P.S.
Really nice to see someone tackle this "formatting html inside php" issue.

**Comment by RiFi2k** [comment]
So you should just be able to set your html format options in code to use spaces instead of tabs, but I will take a closer look to make sure this is happening later today. If it doesn't work out the box right now I can quickly add this.

**Comment by zurkoxxx** [comment]
@RiFi2k nice, thanks!

**Comment by RiFi2k** [comment]
Just want to let you know I didn't forget about you, @zurkoxxx 

I decided to make some major improvements at the same time, so soon it will inherit every configuration possible for HTML formatting from a vscode setting.

- indent-size
- indent-char
- indent-with-tabs
- eol
- end-with-newline
- preserve-newlines
- max-preserve-newlines
- indent-inner-html
- brace-style
- indent-scripts
- wrap-line-length
- wrap-attributes
- wrap-attributes-indent-size
- inline
- unformatted
- content_unformatted
- extra_liners

Also I should be able to grab any .editorconfig values and add those in automatically.

Also looking at formatting inline JS and CSS in PHP files according to the configurations you have set for those as well in code, but I don't know if that will make this release.

Check the [1.2.0](https://github.com/RiFi2k/format-html-in-php/tree/1.2.0) branch if you want to see the progress, it's real close just need to merge the options together better.
