### ISSUE TITLE
Bug when formatting php inside 'script' tags

### ISSUE THREAD

**Issue by tariqalkhassa** [RiFi2k/format-html-in-php#16]
Hello,
if I have a php code inside script tags like this:

```
<script>
<? if (true) { ?>
alert('test');
<? } ?>
</script>
```
a space is being added between '<' and '?' so it becomes like this after formatting :

```
<script>
< ?
if (true) {
    ? >
    alert('test'); <
    ?
} ? >
</script>
```
this problem occures only between script tags

**Comment by RiFi2k** [comment]
@tariqalkhassa what about, seems to work fine

```
<script>
<?php if (true) { ?>
  let objStr = JSON.stringify(obj);
<?php } ?>
</script>
```

Unfortunaly there are too many use cases to support `<?` short open tags, especially when they are discouraged from use anyways.

https://secure.php.net/manual/en/language.basic-syntax.phptags.php

> PHP also allows for short open tag <? (which is discouraged since it is only available if enabled using the short_open_tag php.ini configuration file directive, or if PHP was configured with the --enable-short-tags option).

This extension just uses the HTML portion [JS Beautify](https://github.com/beautify-web/js-beautify)

You can test it out here if you want we are using the same code.

https://beautifier.io/
