### ISSUE TITLE
Allow overriding tab spacing amount

### ISSUE THREAD

**Issue by mrneo240** [RiFi2k/format-html-in-php#17]
```
indent_with_tabs: indentTabs,
    indent_size: config.editor.tabSize,
    indent_char: " ",
```

that is handy that it "just works" but 4 spaces for html indenting is too much for me, but is great for most other languages.

Allowing us to set a custom value would be a nice quality of life enhancement

**Comment by RiFi2k** [comment]
@mrneo240 It's set to the value you have set in your config, so just change it. The HTML settings in the docs are just the example of all the config settings you can over-ride yourself.

`"editor.tabSize": 2`

**Comment by RiFi2k** [comment]
I did change my readme documentation after I read it I could see why you might think as you did.
