### ISSUE TITLE
1.3.2 formatting on save even though that option is false

### ISSUE THREAD

**Issue by richardwo** [RiFi2k/format-html-in-php#2]
Hi,

I think there could be a problem with v1.3.2 - it is formatting when I save a PHP document even though the default setting is still in place` "editor.formatOnSave": false`

When I disable the extension and save files this doesn't happen.

**Comment by RiFi2k** [comment]
Yup, your right. I broke this, I'll fix it ASAP

**Comment by RiFi2k** [comment]
@richardwo Sorry about that man, tried to fix it as soon as I saw your issue.
