### ISSUE TITLE
Error on VS Code Version 1.34.0

### ISSUE THREAD

**Issue by wilo087** [RiFi2k/format-html-in-php#23]
When I try to format any php file always return an error: 
Cannot format 'file-name.php'

![Screen Shot 2019-05-20 at 9 47 13 AM](https://user-images.githubusercontent.com/5408504/58026507-a6bc4800-7ae4-11e9-9649-a35c706d2f6b.png)

**Comment by RiFi2k** [comment]
I think this file hadn't been saved yet thats why it was showing up as /Untitled-1
