### ISSUE TITLE
[Question] Is it possible to use it with `Beautify`

### ISSUE THREAD

**Issue by kanlukasz** [RiFi2k/format-html-in-php#24]
Hi,

I have a question because i'm not sure how your add-on work.
Is your add-on only used to transfer the formatter functionality to php files?

Is it possible to choose formatter that will format my html in php?
I use `Beautify` by `HookyQR` to format html files and i would like to use it for mixed html/php files too

**Comment by RiFi2k** [comment]
Yeah so that would be fine, this plugin only does PHP files and only if you tell it too or you have format on save enabled.
