### ISSUE TITLE
Set up on save as default formatter

### ISSUE THREAD

**Issue by ronilaukkarinen** [RiFi2k/format-html-in-php#40]
Hello! I'm getting "There is no formatter for 'php' files installed." even though I have this installed. So no formatting on saving php files. Also, how to add keybinding for the formatter?

**Comment by RiFi2k** [comment]
Actually this extension is not a formatting extension, you will want to use it in addition to a PHP formatting extension. All this one does is run formatting on the HTML but not during the formatting hook.
Both Q's should be explained [here](https://github.com/RiFi2k/format-html-in-php/blob/master/README.md)

**Comment by ronilaukkarinen** [comment]
Ok, thanks. I already found a plugin for this purpose, [Formatters Hero](https://marketplace.visualstudio.com/items?itemName=Wscats.qf), if someone is curious.
