### ISSUE TITLE
optionsFromVsCode - indent_scripts wrong default

### ISSUE THREAD

**Issue by jacekk015** [RiFi2k/format-html-in-php#41]
indent_scripts is set default as 'normal' - not 'keep'
https://github.com/HookyQR/VSCodeBeautify/blob/master/Settings.md

If you have 'keep' setting, the formatter behaves differently than for normal HTML file

**Comment by RiFi2k** [comment]
I go with the default from the library on this one.
https://github.com/beautify-web/js-beautify/blob/master/tools/template/beautify-html.wrapper.js#L52
