### ISSUE TITLE
Where to change settings

### ISSUE THREAD

**Issue by seanpmgallagher** [RiFi2k/format-html-in-php#42]
I can't figure out where to change the settings. Specifically looking to get rid of the wrap line-length because it looks terrible. "html.format.wrapLineLength": 120 that's the setting I"m trying to change, but can't find it anywhere. I've looked in ~/.vscode/extensions/rifi2k.format-html-in-php-1.6.2, but can't find where that settings is.

**Comment by RiFi2k** [comment]
Your going to configure the HTML formatting settings just like normal so configure
```
"html.format.wrapLineLength"
```
